/*
	this is a part of TVP (KIRIKIRI) software source.
	see other sources for license.
	(C)2001-2007 W.Dee <dee@kikyou.info> and contributors
*/

/* C-language interface to tvpgl_ia32.lib */
/* this file is always generated by summary.pl */

#ifndef __TVPGL_ARM_INTF__
#define __TVPGL_ARM_INTF__

#include "tjsTypes.h"
#include "tvpgl.h"


#endif
